#!/usr/bin/env node
// Reads node_modules/sql.js/dist/sql-wasm.wasm and writes a TS module that
// exposes the bytes as base64. The OpenCode loader passes those bytes to
// initSqlJs() as `wasmBinary`, so sql.js never tries to fopen() the
// `dist/sql-wasm.wasm` path baked in by Emscripten — that path is the
// build host's filesystem layout, which doesn't survive Bun --compile or
// `npm publish` to anyone else's machine.

import { readFileSync, writeFileSync, existsSync } from 'node:fs';
import { dirname, join, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';

const __dirname = dirname(fileURLToPath(import.meta.url));
const REPO_ROOT = resolve(__dirname, '..');
const WASM_PATH = join(REPO_ROOT, 'node_modules', 'sql.js', 'dist', 'sql-wasm.wasm');
const OUT_PATH = join(REPO_ROOT, 'src', 'loaders', 'sql-wasm-inline.ts');

if (!existsSync(WASM_PATH)) {
  console.error(`[inline-wasm] missing ${WASM_PATH}. Run 'npm install' first.`);
  process.exit(1);
}

const wasm = readFileSync(WASM_PATH);
const base64 = wasm.toString('base64');

const banner = '// Auto-generated by scripts/inline-wasm.mjs from node_modules/sql.js/dist/sql-wasm.wasm.\n// Do not edit; rerun `npm run build` to regenerate after sql.js bumps.\n';
writeFileSync(OUT_PATH, `${banner}\nexport const SQL_WASM_BASE64 = '${base64}';\n`);
console.log(`[inline-wasm] wrote ${OUT_PATH} (${(wasm.length / 1024).toFixed(0)} KB raw, ${(base64.length / 1024).toFixed(0)} KB base64)`);
