#!/usr/bin/env node
// Reads the vendored browser libraries (vendor/chart.umd.min.js and
// vendor/tailwind.js) and writes a TS module that exposes their bytes as
// base64. The Hono server serves those bytes from /vendor/* so the dashboard
// never loads Chart.js or Tailwind from an external CDN.
//
// Why: the dashboard used to pull chart.js@4 from jsdelivr and Tailwind from
// cdn.tailwindcss.com. jsdelivr's `chart.js@4` range URL fell into an infinite
// redirect loop (ERR_TOO_MANY_REDIRECTS) for every user, so Chart.js never
// loaded, the dashboard JS crashed on `Chart is not defined` before it ever
// fetched /api/data, and the whole page rendered blank. A local dashboard tool
// must not depend on third-party CDNs — so we bundle both libs and serve them
// ourselves. Same base64-inline trick as scripts/inline-wasm.mjs (which solves
// the same "baked-in path doesn't survive publish/--compile" problem).

import { readFileSync, writeFileSync, existsSync } from 'node:fs';
import { dirname, join, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';

const __dirname = dirname(fileURLToPath(import.meta.url));
const REPO_ROOT = resolve(__dirname, '..');
const VENDOR_DIR = join(REPO_ROOT, 'vendor');
const OUT_PATH = join(REPO_ROOT, 'src', 'vendor-assets.ts');

const ASSETS = [
	{ file: 'chart.umd.min.js', constName: 'CHART_JS_BASE64' },
	{ file: 'tailwind.js', constName: 'TAILWIND_JS_BASE64' },
];

const parts = [];
for (const { file, constName } of ASSETS) {
	const srcPath = join(VENDOR_DIR, file);
	if (!existsSync(srcPath)) {
		console.error(`[inline-vendor] missing ${srcPath}. The vendored libs are committed under vendor/.`);
		process.exit(1);
	}
	const bytes = readFileSync(srcPath);
	const base64 = bytes.toString('base64');
	parts.push({ file, constName, raw: bytes.length, base64 });
}

const banner =
	'// Auto-generated by scripts/inline-vendor.mjs from vendor/*.js.\n' +
	'// Do not edit; rerun `npm run build` to regenerate after bumping a vendored lib.\n';

const body = parts
	.map((p) => `// ${p.file} (${p.raw} bytes raw)\nexport const ${p.constName} = '${p.base64}';\n`)
	.join('\n');

writeFileSync(OUT_PATH, `${banner}\n${body}`);

for (const p of parts) {
	console.log(
		`[inline-vendor] ${p.file} → ${OUT_PATH} (${(p.raw / 1024).toFixed(0)} KB raw, ${(p.base64.length / 1024).toFixed(0)} KB base64)`,
	);
}
